name: Ops Auto-Alerts

on:
  schedule:
    - cron: '0 22 * * 1-5' # Daily after market close
  workflow_dispatch:

concurrency:
  group: forecast-system
  cancel-in-progress: false

jobs:
  check-alerts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Check System Health
        id: health
        run: |
          # Read latest ops report
          if [ -f "dev/ops/forecast/latest.json" ]; then
            STATUS=$(jq -r '.status // "UNKNOWN"' dev/ops/forecast/latest.json)
            RECS=$(jq -r '.recommendations | length' dev/ops/forecast/latest.json)
            P1_COUNT=$(jq -r '[.recommendations[] | select(.level == "P1")] | length' dev/ops/forecast/latest.json)
            
            echo "status=$STATUS" >> $GITHUB_OUTPUT
            echo "recommendations=$RECS" >> $GITHUB_OUTPUT
            echo "p1_count=$P1_COUNT" >> $GITHUB_OUTPUT
          else
            echo "status=MISSING_REPORT" >> $GITHUB_OUTPUT
            echo "recommendations=0" >> $GITHUB_OUTPUT
            echo "p1_count=1" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Alert Issue
        if: steps.health.outputs.p1_count > 0 || steps.health.outputs.status == 'MISSING_REPORT'
        uses: actions/github-script@v7
        with:
          script: |
            const today = new Date().toISOString().split('T')[0];
            const title = `⚠️ Forecast System Alert - ${today}`;
            
            // Check if issue already exists today (rate limit)
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'ops-alert',
              per_page: 10
            });
            
            const existingToday = issues.data.find(i => i.title.includes(today));
            if (existingToday) {
              console.log('Alert already raised today, skipping');
              return;
            }
            
            const body = `## System Health Alert
            
            **Status:** ${{ steps.health.outputs.status }}
            **P1 Recommendations:** ${{ steps.health.outputs.p1_count }}
            
            Please review the ops dashboard and take action.
            
            - Dashboard: \`dev/ops/forecast/index.html\`
            - Latest Report: \`dev/ops/forecast/latest.json\`
            `;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              labels: ['ops-alert', 'forecast', 'auto-generated']
            });
